---
# rhel sets Default requiretty. We need to fix that for ansible to work

- name: "patch sudoers file"
  become: yes
  vars:
    ansible_ssh_pipelining: no
  lineinfile:
    dest: /etc/sudoers.tmp
    line: 'Defaults   requiretty'
    state: absent

- name: Final sudoers file check
  become: yes
  shell: "visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers"
