---
- name: Disable boot-time yum update
  become: yes
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    state: absent
    regexp: '^.*yum\s-y\supdate.*$'

- name: Apply security patches
  become: yes
  shell: yum update-minimal --security -y

- name: Add optional RHEL repo
  become: yes
  command: yum-config-manager --enable rhel-7-server-optional-rpms

- name: Install ntp
  command: yum install ntp
  become: true

- name: Add amazon ntp server to ntp.conf
  lineinfile:
    path: /etc/ntp.conf
    insertafter: EOF
    line: 'server 169.254.169.123 prefer iburst'
  become: yes

- name: Restart ntpd
  service:
    name: ntpd
    state: restarted
  become: yes
