---
##
# Mounts Jenkins Data EBS Volume
##
- name: Gather EC2 Metadata
  ec2_metadata_facts:

- name: EBS - Attach Volume
  become: true
  ec2_vol:
    instance: "{{ ansible_ec2_instance_identity_document_instanceid }}"
    name: bfd-jenkins-data
    device_name: /dev/sdf
    region: "{{ ansible_ec2_placement_region }}"
  register: ec2_vol

- name: EBS - Mounting the filesystem
  become: yes
  mount:
    name: /var/lib/jenkins_home
    src: /dev/nvme1n1
    fstype: ext4
    state: mounted
