---
##
# Mounts Jenkins Data EBS Volume
##
- name: Gather EC2 Metadata
  ec2_metadata_facts:
  become: yes

- name: Attach EBS Volume
  become: yes
  become_user: root
  ec2_vol:
    instance: "{{ ansible_ec2_instance_identity_document_instanceid }}"
    name: bfd-jenkins-data
    device_name: /dev/nvme1n1
    region: "{{ ansible_ec2_placement_region }}"
  register: ec2_vol

- name: mounting the filesystem
  become: yes
  mount:
    name: /var/lib/jenkins_home
    src: /dev/nvme1n1
    fstype: ext4
    state: mounted
