---
- name: Create download directory
  file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: /tmp/downloads

- name: Download Maven
  get_url:
    url: wget http://apache-mirror.8birdsvideo.com/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz
    dest: /tmp/downloads
    checksum: sha512:https://www.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz.sha512

- name: Install Maven
  unarchive:
    src: /tmp/downloads/apache-maven-3.6.1-bin.tar.gz
    dest: /opt/maven/
    copy: no
    owner: root
    group: root
    mode: 'go-w'

- name: Create symlink to make mvn command available to all users
  file:
    src: /opt/maven/bin/mvn
    dest: /usr/bin/mvn
    owner: root
    group: root
    state: link
